name: py-liccheck
author: Anderson Banihirwe
description: Check license of Python packages and their dependencies.
inputs:
  strategy-ini-file:
    description: Path to a strategy ini file or pyproject.toml file to use.
    required: false
    default: ./pyproject.toml
  level:
    description: Level for testing compliance of packages.
    required: false
    default: STANDARD
  requirements-txt-file:
    description: Path to a requirements.txt file to use.
    required: false
    default: ./requirements.txt
  reporting-txt-file:
    description: Path to a reporting.txt file to use.
    required: false
    default: liccheck-report.txt
  no-deps:
    description: Whether not to check dependencies.
    required: false
  liccheck-version:
    description: Set the liccheck package version.
    required: false
    default: 0.6.4

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: check-square
  color: 'green'
